import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Inter } from "next/font/google";
import { currentUserType } from "@/types/main";
import Providers from "./providers/Providers";
import { createClient } from "@/lib/supabase/server";
import { redirect } from "next/navigation";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const supabase = await createClient();
  const {
    data: { session },
  } = await supabase.auth.getSession();

  const user = session?.user;

  const { data, error } = await supabase
    .from("profiles")
    .select("*")
    .eq("id", user?.id)
    .single();

  if (error) {
    console.log(error);
  }

  const [f, l] = user?.user_metadata.full_name.split(" ") || "Unknown";
  const avatar_name = (f[0] + l[0]).toUpperCase();
  const role = data?.role;

  const currentUser: currentUserType = {
    id: user?.id || "",
    name: user?.user_metadata.full_name ?? "Unknown",
    avatar: data?.avatar_url || avatar_name,
    role,
    job_title: data?.job_title || "Unknown Job",
  };

  return (
    <>
      <html
        lang="en"
        suppressHydrationWarning
        className={`${geistSans.variable} ${geistMono.variable} ${inter.variable} h-full antialiased`}
      >
        <body className="min-h-full flex flex-col">
          <Providers currentUser={currentUser}>{children}</Providers>
        </body>
      </html>
    </>
  );
}
